apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: order-service-network-delay
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/name: order-service
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "0ms"
  direction: to
  target:
    selector:
      labelSelectors:
        app.kubernetes.io/name: kafka
    mode: all
  duration: '2m'
  scheduler:
    cron: '@every 10m'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: inventory-service-network-delay
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/name: inventory-service
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "0ms"
  direction: to
  target:
    selector:
      labelSelectors:
        app.kubernetes.io/name: kafka
    mode: all
  duration: '2m'
  scheduler:
    cron: '@every 10m'
