{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "edge-proxy.fullname" . }}
  labels:
    {{- include "edge-proxy.labels" . | nindent 4 }}
    release: observability
spec:
  selector:
    matchLabels:
      {{- include "edge-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: /metrics
      interval: 15s
{{- end }}
