apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-proxy.fullname" . }}
  labels:
    {{- include "edge-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: 9090
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "edge-proxy.selectorLabels" . | nindent 4 }}
