apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sre-sandbox
  source:
    repoURL: 'https://github.com/alecjvaughn/SRE_Sandbox_ERP.git'
    path: helm/observability
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-kind.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
