apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: default
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 1G
  configOverrides:
    jvm:
      - "-Xmx256M"
      - "-Xms256M"
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: default
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 1G
  configOverrides:
    jvm:
      - "-Xmx256M"
      - "-Xms256M"
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
        namespace: default
